lpau/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('external.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^account/login/$', auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(r'^account/logout/$', auth_views.logout,
        {'template_name': 'accounts/logged_out.html'}, name='logout'),

    url(r'^membership/', include('membership.urls')),
] + staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

membership/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views


app_name = 'membership'
urlpatterns = [
    # /membership/
    url(r'^$', views.IndexView.as_view(), {'sidebar': 'index'}, name='index'),
    # /membership/student_work
    url(r'^student_work/$', views.StudentWorkView.as_view(),
        {'sidebar': 'student_work'}, name='student_work'),
    # /membership/bbs/<pk>/
    url(r'^bbs/$', RedirectView.as_view(url='1/')),
    url(r'^bbs/(?P<pk>\d+)/$', views.ThreadView.as_view(),
        {'sidebar': 'bbs'}, name='bbs'),
    # /membership/download_document/
    url(r'^download_document/$', views.DownloadDocumentView.as_view(),
        {'sidebar': 'download_document'}, name='download_document'),
    url(r'^download_file/(?P<difficulty>\w+)/(?P<date>\d+)/$', views.DownloadFileView.as_view(),
        name='download_file'),
    # /membership/schedule/
    # /membership/teachers/
    url(r'^teachers/$', views.TeachersView.as_view(),
        {'sidebar': 'teachers'}, name='teachers'),
    # /membership/example/
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bbs/', include('bbs.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filemanager/', include('filemanager.urls', namespace='filemanager'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

membership/models.py
from django.db import models
from django.contrib.auth.models import User


class Thread(models.Model):
    title = models.CharField("タイトル", max_length=200, blank=False)
    message = models.TextField("メッセージ", blank=False)
    pub_date = models.DateTimeField("作成日時", auto_now_add=True, editable=False)

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = "スレッド"
        verbose_name_plural = "スレッド"

class Comment(models.Model):
    user = models.ForeignKey(User, verbose_name="ユーザ")
    thread = models.ForeignKey(Thread, verbose_name="スレッド")
    message = models.CharField("メッセージ", max_length=500, blank=False)
    pub_date = models.DateTimeField("投稿日時", auto_now_add=True, editable=False)

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = "コメント"
        verbose_name_plural = "コメント"

class StudentWork(models.Model):
    """生徒の作品"""
    user = models.ForeignKey(User, verbose_name="ユーザ")
    file_name = models.CharField("ファイル名", max_length=50)
    data = models.FileField("データ", upload_to='student_works')
    pub_date = models.DateTimeField("アップロード日時", auto_now_add=True, editable=False)

    def __str__(self):
        return self.file_name

    class Meta:
        verbose_name = verbose_name_plural = "生徒の作品"

membership/forms.py
from django.forms import ModelForm

from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ('thread',)

membership/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from util.views import CommonView
from util.views import CommonTemplateView
from django.views.generic import FormView
from util.views import CommonDetailView
from util.views import CommonListView
from datetime import datetime

from .models import Thread, Comment, StudentWork
from .forms import CommentForm

class StudentWorkView(CommonListView):
    model = StudentWork
    context_object_name = 'student_work_list'

class IndexView(CommonTemplateView):
    template_name = 'membership/index.html'

class TeachersView(CommonListView):
    template_name = 'membership/teachers.html'
    context_object_name = 'teachers'
    teachers = [
        {'name': '小木曽 聖', 'kana': 'おぎそ あきら',
            'introduction': '趣味は読書とプログラミング\nおすすめの本はバーティミアス。Atcoder(プログラミングコンテスト)とかたまに出る。\n最近は料理とかスポーツにも手を出し始めた。',
            'to_students': '「好きこそものの上手なれ」ってことで、好きになるとこから始めよう！'},
        {'name': '山根 茂之', 'kana': 'やまね しげゆき',
            'introduction': '電気通信大学3年生。趣味はサイクリング。音声に興味を持ち始める。',
            'to_students': 'プログラミングは楽しいものですが、できるようになるには相当な時間が必要です。この教室でプログラミングの楽しさや難しさを学んでもらえたら嬉しいです。また家でちゃんと復習することも大切ですよ。'},
        {'name': '風間 健流', 'kana': 'かざま たける',
            'introduction': '機械いじりと釣りが趣味。\n最近のマイブームは古本屋巡りです。\nゲーム作成サークルのx680x0同好会に所属。',
            'to_students': 'プログラミングは最初は難しいかもしれません。でもコツをつかめばいろいろなことができるようになり、とてもおもしろくなります。一緒に頑張りましょう！'},
        {'name': '宮澤 修', 'kana': 'みやざわ おさむ',
            'introduction': '横浜市出身・在住\n情報理工学部　情報・通信工学科3年　コンピュータサイエンスコース（コンピュータの仕組みについて学ぶところです）\n好きなゲーム　星のカービィ、MOTHER(1, 2)',
            'to_students': 'プログラミングは一人でやるより、仲間と共にやっていく方が面白いし、上達します（体験談）。気軽に相談してください。一緒に楽しみながら腕を磨きましょう。'},
        {'name': '張 翌坤', 'kana': 'ちょう よくこん',
            'introduction': '中国から来た留学生です。テレビゲームが好きで、スマホゲームが嫌い。みんなに好かれる先生になりたいなぁ〜',
            'to_students': 'pythonは本当に簡単で優れた言語です。この教室を通して、最終的にこのプログラミング力がみんなの勉強や生活の助けになれるなら嬉しいです。'},
        {'name': '栁 裕太', 'kana': 'やなぎ ゆうた',
            'introduction': '学部2年総合情報学科\nプログラミングデビューは中3でした\n日々エラーとテストに頭を抱える日々',
            'to_students': '誰にでも凄いものが作れる時代になりました。\n自分は何が作れるのか、考えてみましょう。\nきっと、実現できますよ。'},
        {'name': '佐藤 海斗', 'kana': 'さとう かいと',
            'introduction': 'プログラミングは大学生から本格的に始める。アニメ・釣り・アウトドアなどが好きです。ロボメカ工房フライト部隊に所属。最近はドローンの制作や新入生に向けたArduino講習の準備をしています。',
            'to_students': 'プログラミングは最初のうちは楽しめないと思います。しかし、ある程度できるようになれば楽しくなってくると思うので頑張りましょう！一緒に頑張っていきましょう！'},
        {'name': '長安 尚之', 'kana': 'ながやす なおゆき',
            'introduction': '埼玉都民の長安です！\n趣味はアニメと落語（聞く方）。\nでも『じょしらく』はあんまり見てません。',
            'to_students': 'わかると楽しいのがプログラミング。\nわからないところがあったら、\n一緒に考えていこう！'},
        {'name': '南条 宏貴', 'kana': 'なんじょう ひろき',
            'introduction': 'うどんの王国、香川県出身の南条です！大学一年！趣味はバレーボールで、大学でもバレーボール部に入部しています！プログラミングも本格的に始めたのは大学に入ってからなので、初心者ですが一生懸命頑張ります！',
            'to_students': '楽しみながら自然と力がつく教室を目指しています！\n一緒に頑張りましょう！'},
    ]

    def get_queryset(self):
        return self.teachers

class ThreadView(FormView, CommonDetailView):
    template_name = 'membership/thread.html'
    model = Thread
    form_class = CommentForm
    success_url = './'

    def get_context_data(self, **kwargs):
        # 表示するスレッド
        context = super(FormView, self).get_context_data(**kwargs)
        thread = get_object_or_404(Thread, pk=self.kwargs.get(self.pk_url_kwarg))
        context['comment_list'] = thread.comment_set.all().order_by('id')

        return context

    def form_valid(self, form):
        form.instance.username = self.request.user.username
        form.instance.thread = get_object_or_404(Thread, pk=self.kwargs.get(self.pk_url_kwarg))
        form.instance.save()

        return super(ThreadView, self).form_valid(form)


# 講義資料リスト: linkは django_project_root/files/documents/ の中を指している
# TODO: 表示時に順番が逆転してしまう可能性有
document_list = {
    'entry': [
        {'file_name': 'lpau_entry1_20160508.pptx', 'link': '1.pptx',
            'date': '20160508', 'datetime': datetime(2016, 5, 8)},
        {'file_name': 'lpau_entry2_20160512.pptx', 'link': '2.pptx',
            'date': '20160512', 'datetime': datetime(2016, 5, 12)},
        {'file_name': 'lpau_entry3_20160522.pptx', 'link': '3.pptx',
            'date': '20160522', 'datetime': datetime(2016, 5, 22)},
        {'file_name': 'lpau_entry4_20160529.pptx', 'link': '4.pptx',
            'date': '20160529', 'datetime': datetime(2016, 5, 29)},
        {'file_name': 'lpau_entry5_20160605.pptx', 'link': '5.pptx',
            'date': '20160605', 'datetime': datetime(2016, 6, 5)},
        {'file_name': 'lpau_entry6_20160612.pptx', 'link': '6.pptx',
            'date': '20160612', 'datetime': datetime(2016, 6, 12)},
        {'file_name': 'lpau_entry7_20160619.pptx', 'link': '7.pptx',
            'date': '20160619', 'datetime': datetime(2016, 6, 19)},
    ],
    'basic': [
        {'file_name': 'lpau_basic1_20160522.pdf', 'link': '1.pdf',
            'date': '20160522', 'datetime': datetime(2016, 5, 22)},
        {'file_name': 'lpau_basic2_20160529.pdf', 'link': '2.pdf',
            'date': '20160529', 'datetime': datetime(2016, 5, 29)},
        {'file_name': 'lpau_basic3_20160605.pdf', 'link': '3.pdf',
            'date': '20160605', 'datetime': datetime(2016, 6, 5)},
        {'file_name': 'lpau_basic4_20160619.pdf', 'link': '4.pdf',
            'date': '20160619', 'datetime': datetime(2016, 6, 19)},
    ],
}

class DownloadDocumentView(CommonListView):
    template_name = 'membership/download_document.html'
    context_object_name = 'document_list'

    def get_queryset(self):
        return document_list

class DownloadFileView(CommonView):
    def get(self, request, *args, **kwargs):
        date = kwargs['date']
        difficulty = kwargs['difficulty']
        for document in document_list[difficulty]:
            if document['date'] == date:
                link = document['link']
                file_name = document['file_name']

        response = HttpResponse(
            open('files/documents/' + difficulty + link, 'rb').read(),
            content_type='application/octet-stream'
        )
        response['Content-Disposition'] = 'attachment; filename = "' + file_name + '"'

        return response

membership/templates/membership/download_document.html
{% extends "base_membership.html" %}

{% block title %}授業資料ダウンロード&nbsp;|&nbsp;{% endblock %}

{% block content_membership %}
<div id="description" class="row-fluid section">
  <h3>授業資料ダウンロード</h3>
  <span>
    ここには説明文を入れる。<br>
    今は仮の文章を入れている。
  </span>
</div>

<div id="document-list" class="row-fluid section">
  {% for difficulty, documents in document_list.items %}
  <div class="panel panel-default" style="margin-bottom: 20px;">
    <div class="list-group panel-body">
      {% for document in documents %}
      <a class="list-group-item" href="{% url 'membership:download_file' difficulty=difficulty date=document.date %}">
        <h4 class="list-group-item-heading">
          {{ document.file_name }}
          <small>実施日:&nbsp;{{ document.datetime|date:'Y年m月d日' }}</small>
        </h4>
        <p class="list-group-item-text">
          {# 未実装 #}
          {{ document.description }}
        </p>
      </a>
      {% endfor %}
    </div>
    {% comment %}
    <nav class="panel-footer text-center">
      <ul class="pagination" style="margin-top: 2px; margin-bottom: 2px;">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
    {% endcomment %}
  </div>
  {% endfor %}
</div>
{% endblock content_membership %}

membership/templates/membership/index.html
{% extends "base_membership.html" %}

{% block title %}Top&nbsp;|&nbsp;{% endblock %}

{% block content_membership %}
<div id="description" class="row-fluid section">
  <h4>
    このHPでは、生徒がプログラミング力を向上させる教室以外の場として、プログラミングに関する情報の提供・交流を行います。また、保護者様が教室の状況をご理解いただくための場でもあります。
  </h4>
</div>

<div id="news" class="row-fluid section">
  <div class="panel panel-default" style="margin-bottom: 5px;">
    <div class="panel-heading">新着ニュース</div>
    <div class="list-group panel-body">
      <a class="list-group-item" href="#" class="disable">
        2016年6月19日&nbsp;子供のためのプログラミング教室&nbsp;第7回を実施しました。
      </a>
      <a class="list-group-item" href="#" class="disable">
        2016年6月12日&nbsp;子供のためのプログラミング教室&nbsp;第6回を実施しました。
      </a>
      <a class="list-group-item" href="#" class="disable">
        2016年6月5日&nbsp;子供のためのプログラミング教室&nbsp;第5回を実施しました。
      </a>
      <a class="list-group-item" href="#" class="disable">
        2016年5月29日&nbsp;子供のためのプログラミング教室&nbsp;第4回を実施しました。
      </a>
      <a class="list-group-item" href="#" class="disable">
        2016年5月22日&nbsp;子供のためのプログラミング教室&nbsp;第3回を実施しました。
      </a>
    </div>
    {% comment %}
    <nav class="panel-footer" style="text-align: center;">
      <ul class="pagination" style="margin-top: 2px; margin-bottom: 2px;">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
    {% endcomment %}
  </div>
</div>
{% endblock content_membership %}

membership/templates/membership/studentwork_list.html
{% extends "base_membership.html" %}
{% load static %}

{% block title %}生徒作品&nbsp;|&nbsp;{% endblock %}

{% block content_membership %}
<script type="text/javascript">
  $(function(){
    $('.python')
      .each(function(i, block){
        hljs.highlightBlock(block);
      });
  });
</script>
<div id="description" class="row-fluid section">
  <h3>生徒作品</h3>
  <span>
    ここには説明文を入れる。<br>
    今は仮の文章を入れている。
  </span>
</div>

<div id="studentwork-list" class="row-fluid section">
  {% for student_work in student_work_list %}
  <div class="panel panel-default" style="margin-bottom: 20px;">
    <div class="panel-heading">
      {{ student_work.file_name|safe }}
    </div>
    <div class="panel-body">
      <pre><code id="student_work_{{ student_work.id }}"
        class="python">{{ student_work.data.read|safe }}</code></pre>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content_membership %}

membership/templates/membership/teachers.html
{% extends "base_membership.html" %}
{% load staticfiles %}

{% block title %}講師紹介&nbsp;|&nbsp;{% endblock %}

{% block content_membership %}
<div id="description" class="row-fluid section">
  <h3>講師紹介</h3>
  <span>
    ここには説明文を入れる。<br>
    今は仮の文章。<br>
  </span>
</div>

<div id="news" class="row-fluid section">
  {% for teacher in teachers %}
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="thumbnail">
      <img src="{% static 'img/shadow.png' %}" class="img-rounded">
      <div class="caption">
        <h3>{{ teacher.name }}<br class="visible-sm"><small>（{{ teacher.kana }}）</small></h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <h4 class="list-group-item-heading">
            自己紹介
          </h4>
          <p class="list-group-item-text">
            {{ teacher.introduction|linebreaksbr }}
          </p>
        </li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading">
            みんなへ
          </h4>
          <p class="list-group-item-text">
            {{ teacher.to_students|linebreaksbr }}
          </p>
        </li>
      </ul>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content_membership %}

membership/templates/membership/thread.html
{% extends "base_membership.html" %}

{% block title %}質問掲示板&nbsp;|&nbsp;{% endblock %}

{% block content_membership %}
<div id="description" class="row-fluid section">
  <h3>質問掲示板</h3>
  <span>
    ここには説明文を入れる。<br>
    今は仮。まる。
  </span>
</div>

<div id="bbs" class="row-fluid section">
  <div class="list-group">
    {% for comment in comment_list %}
    <a id="comment-{{ comment.id }}" class="list-group-item" href="#comment-{{ comment.id }}">
      <div class="list-group-item-heading">
        <h4 class="comment-user">
          {{ comment.user.last_name }}&nbsp;{{ comment.user.first_name }}
          <small class="comment-date">{{ comment.pub_date }}</small>
        </h4>
      </div>
      <p class="list-group-item-text">
        {{ comment.message }}
      </p>
    </a>
    {% endfor %}
  </div>

  <form action="{{ form.action }}" method="post">
    <div class="form-group">
      <label for="id_{{ form.message.name }}">メッセージ</label>
      <input id="id_{{ form.message.name }}" type="text" name="{{ form.message.name }}" maxlength="500"
        class="form-control">
    </div>
    {% csrf_token %}
    <input type="hidden" name="{{ form.user.name }}" value="{{ user.id }}">
    <button type="submit" class="btn btn-default">投稿</button>
  </form>
</div>
{% endblock content_membership %}