accounts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    # /account/login/
    url(r'^login/$', auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    # /account/logout/
    url(r'^logout/$', auth_views.logout,
        {'template_name': 'accounts/logged_out.html'},
        name='logout'),
    # /account/password_change/
    url(r'^password_change/$', auth_views.password_change,
        {
            'template_name': 'accounts/password_change.html',
            'post_change_redirect': reverse_lazy('account:password_change_done'),
        },
        name='password_change'),
    # /account/password_change_done/
    url(r'^password_change_done/$', auth_views.password_change_done,
        {'template_name': 'accounts/password_change_done.html'},
        name='password_change_done'),
]

lpau/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('external.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^account/login/$', auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(r'^account/logout/$', auth_views.logout,
        {'template_name': 'accounts/logged_out.html'}, name='logout'),

    url(r'^membership/', include('membership.urls')),
] + staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bbs/', include('bbs.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filemanager/', include('filemanager.urls', namespace='filemanager'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}

{% block title %}ログアウト{% endblock title %}

{% block content %}

    <h3 class="page-header">ログアウトしました</h3>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<div id=content" class="row-fluid">
  <form method="post" action="{% url 'account:login' %}"
    class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
    <div class="form-group">
      <label for="id_username">
        {{ form.username.label }}
      </label>
      <input id="id_username" class="form-control" maxlength="254" name="username" type="text">
    </div>
    <div class="form-group">
      <label for="id_password">
        {{ form.password.label }}
      </label>
      <input id="id_password" class="form-control" name="password" type="password">
    </div>
    <div class="form-group">
      <input class="btn btn-success" type="submit" value="ログイン">
    </div>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
  </form>
</div>

{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block title %}パスワードの変更&nbsp;|&nbsp;{% endblock %}

{% block content %}
<div id="content" class="row-fluid">
  <div id="description" class="row-fluid section">
    <h3>パスワードの変更</h3>
  </div>
  <form method="post" action=""
    class="col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2">
    {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label for="{{ field.id_for_label }}" class="control-label">
          {{ field.label }}
        </label>
        <input id="{{ field.id_for_label }}" name="{{ field.html_name }}"
          type="password" class="form-control">
        <span class="help-block">
          {% for error in field.errors %}
            <strong>{{ error }}</strong><br>
          {% endfor %}
          {{ field.help_text|safe }}
        </span>
      </div>
    {% endfor %}
    {% csrf_token %}
    <input type="submit" class="btn btn-warning" value="変更">
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block title %}パスワード変更完了&nbsp;|&nbsp;{% endblock %}

{% block content %}
<div id="content" class="row-fluid">
  <div id="description" class="row-fluid section">
    <h3>パスワード変更完了</h3>
  </div>
</div>
{% endblock content %}